language: cpp
dist: trusty
compiler:
  - gcc

# https://docs.travis-ci.com/user/languages/cpp/#gcc-on-linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  # workaround broken travis NO_PUBKEY error which is supposedly triggered by adding `ubuntu-toolchain-r-test`,
  # because `apt update` tries to reload `https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu trusty InRelease`.
  # Taked from https://github.com/purpleidea/mgmt/commit/4e42d9ed0300995df3f2ef00724b2a837bc2a971
  - if [ -e /etc/apt/sources.list.d/rabbitmq_rabbitmq-server.list ]; then sudo rm -f /etc/apt/sources.list.d/rabbitmq_rabbitmq-server.list; fi

install:
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      sudo bash .travis/install_intel_opencl.sh;
    fi;

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELWITHDEBINFO ..
  - make -j4
  - cd ..
  - ./build/aplusb
